//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafeteria
    {
        public int cafID { get; set; }
        public string nombreCaf { get; set; }
        public string descripcionCaf { get; set; }
        public int localID { get; set; }
        public int productoID { get; set; }
    
        public virtual Local Local { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
