//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReporteDBEntities2 : DbContext
    {
        public ReporteDBEntities2()
            : base("name=ReporteDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cafeteria> Cafeterias { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Queja> Quejas { get; set; }
        public virtual DbSet<Reclamo> Reclamos { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TipoDeReclamo> TipoDeReclamoes { get; set; }
        public virtual DbSet<TipoProducto> TipoProductoes { get; set; }
        public virtual DbSet<tipoQueja> tipoQuejas { get; set; }
        public virtual DbSet<tipoStatu> tipoStatus { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
