//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queja
    {
        public int QuejaID { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int depID { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int tipoQuejaID { get; set; }
        public Nullable<int> statusID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Status Status { get; set; }
        public virtual tipoQueja tipoQueja { get; set; }
    }
}
